"""initial schema

Revision ID: 6927b898dfd4
Revises: 
Create Date: 2026-03-28 05:56:41.890986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6927b898dfd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('distance_miles', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('walk_minutes', sa.Integer(), nullable=True),
    sa.Column('listing_type', sa.String(length=50), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=True),
    sa.Column('pets_allowed', sa.Boolean(), nullable=True),
    sa.Column('available_date', sa.Date(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('urgency_score', sa.Integer(), nullable=True),
    sa.Column('negotiability_score', sa.Integer(), nullable=True),
    sa.Column('incentives', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('deal_classification', sa.String(length=20), nullable=True),
    sa.Column('outreach_suggestion', sa.Text(), nullable=True),
    sa.Column('deal_score', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('price_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_source_source_id')
    )
    op.create_index('idx_listings_active', 'listings', ['is_active'], unique=False)
    op.create_index('idx_listings_deal_score', 'listings', [sa.literal_column('deal_score DESC')], unique=False)
    op.create_index('idx_listings_price', 'listings', ['price'], unique=False)
    op.create_index('idx_listings_source', 'listings', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_listings_source', table_name='listings')
    op.drop_index('idx_listings_price', table_name='listings')
    op.drop_index('idx_listings_deal_score', table_name='listings')
    op.drop_index('idx_listings_active', table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
